application: gae-scores
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /templates
  static_dir: templates
  application_readable: true

- url: /res
  static_dir: res

- url: /
  script: handlers.main.app

- url: /comment/new
  script: handlers.new_comment.app
  login: required

- url: /scores/comments
  script: handlers.list_comments.app

- url: /teams/list
  script: handlers.list_team.app

- url: /teams/new
  script: handlers.new_team.app
  login: required

- url: /teams/delete
  script: handlers.delete_team.app
  login: required

- url: /teams/scores
  script: handlers.list_scores.app

- url: /scores/new
  script: handlers.new_score.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"